CREATE TABLE IF NOT EXISTS username (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS codeItem (
    username VARCHAR(50) NOT NULL UNIQUE,
    codeNumber VARCHAR(50) NOT NULL UNIQUE,
    item VARCHAR(50) NOT NULL UNIQUE,
    PRIMARY KEY (username, item),
    FOREIGN KEY (username) REFERENCES username (username),
    FOREIGN KEY (item) REFERENCES gameitem (item),
);

CREATE TABLE IF NOT EXISTS gameitem (
    id SERIAL PRIMARY KEY,
    item VARCHAR(50) NOT NULL UNIQUE,
    description_item VARCHAR(100) NOT NULL UNIQUE,
);

CREATE TABLE IF NOT EXISTS itemPrice (
    id SERIAL PRIMARY KEY,
    FOREIGN KEY (item) REFERENCES gameitem (item),
    item VARCHAR(50) NOT NULL UNIQUE,
    havePromotion BOOLEAN DEFAULT FALSE,
    price FLOAT NOT NULL,
    pricePromotion FLOAT NOT NULL,
    open_sell TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    close_sell TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);